In [1]:
import numpy
import matplotlib

In [2]:
def sigmoid(x):
    sigmoid = 1/(1 + numpy.exp((-4 * x)))
    return sigmoid

In [3]:
def seq_module(y, t, weights):
    y = numpy.insert(y, 0, 1)
    y = numpy.insert(y, 4, 1)
    y = sigmoid(numpy.dot(weights, y))
    return (y, t+1)

Initializations

In [51]:
weights = numpy.random.uniform(-1, 1, (4, 3, 5))
y = numpy.array([0, 0, 0])
t = 0
y_desired = numpy.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
alpha = 0.5

In [70]:
(y_hat, t) = seq_module(y, t, weights)
print y_hat

[[ 0.00854165  0.05732403  0.01584338]
 [ 0.98757285  0.95047964  0.8755662 ]
 [ 0.0592867   0.98913628  0.04201982]
 [ 0.98926123  0.9967066   0.54928014]]


In [71]:
def calc_lambda(k, t, delta):
    p = calc_p(k, t)
    p_k = 1
    p_k_total = 1
    p_total = 0
    for i in range(delta):
        p_k *= calc_p(k, t-delta)
    for i in range(4):
        for j in range(delta):
            p_k_total *= calc_p(j, t-delta) 
        p_total += p_k_total
    lambda_k = p_k/p_total
    return lambda_k

In [72]:
def calc_p(k, t):
    if t <= 0:
        return 0.25
    else:
        return numpy.exp(-E(k, t)/calc_sigma(alpha, t)**2)

In [73]:
def E(k, t):
    error = y_desired[t] - y_hat[k]
    error = (0.5) * (numpy.sum(error)**2)
    return error

In [74]:
def calc_sigma(alpha, t):
    error = list()
    sum_part = 0
    if t == 0:
        return 3
    else:
        for i in range(4):
            for j in range(4):
                error.append(E(j, t-1))
            sum_part += min(error)            
        sigma = alpha*calc_sigma(alpha, t-1) + (1-alpha)*sum_part*0.25
        return sigma

In [75]:
def response_selection(t, y_hat)

0.593125351439
