In [15]:
import numpy
import matplotlib

In [16]:
def get_weights_k(weights, k, t, y, y_hat, eta):
    if t == 0:
        return numpy.random.uniform(0, 1, (3, 5))
    else:
        temp = eta * calc_lambda(k, r, delta)*y_hat*(1-y_hat)
        return numpy.dot(temp, y)

In [17]:
def sigmoid(x):
    sigmoid = 1/(1 + numpy.exp((-4 * x)))
    return sigmoid

In [18]:
def seq_module(y, t, weights):
    y = numpy.insert(y, 0, 1)
    if t == 0:
        y = numpy.insert(y, 4, 1)
    else:
        y = numpy.insert(y, 4, 0)
    y_hat = sigmoid(numpy.dot(weights, y))
    return (y_hat, t+1)

Initializations

In [19]:
weights = numpy.random.uniform(-1, 1, (4, 3, 5))
y = numpy.array([0, 0, 0])
t = 0
y_desired = numpy.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
alpha = 0.5

In [20]:
(y_hat, t) = seq_module(y, t, weights)
print y_hat

[[ 0.73008397  0.57719746  0.00166994]
 [ 0.65569632  0.99152375  0.12806343]
 [ 0.04263435  0.19071392  0.05712254]
 [ 0.15647644  0.77607589  0.92622731]]


In [27]:
def calc_lambda(k, t, delta):
    p = calc_p(k, t)
    p_k = 1
    p_k_total = 1
    p_total = 0
    for i in range(delta):
        p_k *= calc_p(k, t-i)
    for i in range(4):
        for j in range(delta):
            p_k_total *= calc_p(i, t-j) 
        p_total += p_k_total
    lambda_k = p_k/p_total
    return lambda_k

In [22]:
def calc_p(k, t):
    if t <= 0:
        return 0.25
    else:
        return numpy.exp(-E(k, t)[1]/calc_sigma(alpha, t)**2)

In [23]:
def E(k, t):
    error = y_desired[t] - y_hat[k]
    error_sum = (0.5) * (numpy.sum(error)**2)
    return (error, error_sum)

In [24]:
def calc_sigma(alpha, t):
    error = list()
    sum_part = 0
    if t == 0:
        return 3
    else:
        for i in range(4):
            for j in range(4):
                error.append(E(j, t-1)[1])
            sum_part += min(error)            
        sigma = alpha*calc_sigma(alpha, t-1) + (1-alpha)*sum_part*0.25
        return sigma

In [25]:
def response_selection(t, y_hat, y_desired):
    sum_part = 0
    for k in range(4):
        sum_part += y_hat[k]*calc_lambda(k, t, delta)
    return numpy.argmax(y_desired[t-1] + sum_part)

In [26]:
print response_selection(t, y_hat, y_desired)

NameError: global name 'delta' is not defined